In [1]:
import numpy as np

In [2]:
my_array=np.array([1,2,3,4,5])
my_array

array([1, 2, 3, 4, 5])

In [4]:
list1=[1,2,3,4,5]
list2=[5,6,7,8,9]
lists=[list1+list2]

In [5]:
array_new=np.array(lists)

In [6]:
array_new

array([[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]])

In [7]:
list_notplus=[list1,list2]

In [8]:
array_notplus=np.array(list_notplus)
array_notplus

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros(5,5)

TypeError: data type not understood

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones(5,5)

TypeError: data type not understood

In [14]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
array_notplus.dtype

dtype('int32')

In [17]:
(np.zeros(5)).dtype

dtype('float64')

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(1,50,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [22]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [23]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])