In [3]:
import numpy as np

In [11]:
from __future__ import division

In [12]:
5/2

2.5

In [6]:
ara=np.array([[1,2,3,4],[5,6,7,8]])
ara

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
ara*ara

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [14]:
1/ara

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [16]:
1+(1/ara)

array([[2.        , 1.5       , 1.33333333, 1.25      ],
       [1.2       , 1.16666667, 1.14285714, 1.125     ]])

In [17]:
ara**ara

array([[       1,        4,       27,      256],
       [    3125,    46656,   823543, 16777216]])

In [18]:
ara-ara

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
ara[0:3]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
ara[0][2]

3

In [23]:
ara[0:1]

array([[1, 2, 3, 4]])

In [30]:
ara[0:1]

array([[1, 2, 3, 4]])

In [33]:
#transpose matrix


In [40]:
ara2=(np.arange(1,51)).reshape(10,5)

In [41]:
ara2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [42]:
ara2.T

array([[ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]])

In [43]:
np.dot(ara2,ara2.T)

array([[   55,   130,   205,   280,   355,   430,   505,   580,   655,
          730],
       [  130,   330,   530,   730,   930,  1130,  1330,  1530,  1730,
         1930],
       [  205,   530,   855,  1180,  1505,  1830,  2155,  2480,  2805,
         3130],
       [  280,   730,  1180,  1630,  2080,  2530,  2980,  3430,  3880,
         4330],
       [  355,   930,  1505,  2080,  2655,  3230,  3805,  4380,  4955,
         5530],
       [  430,  1130,  1830,  2530,  3230,  3930,  4630,  5330,  6030,
         6730],
       [  505,  1330,  2155,  2980,  3805,  4630,  5455,  6280,  7105,
         7930],
       [  580,  1530,  2480,  3430,  4380,  5330,  6280,  7230,  8180,
         9130],
       [  655,  1730,  2805,  3880,  4955,  6030,  7105,  8180,  9255,
        10330],
       [  730,  1930,  3130,  4330,  5530,  6730,  7930,  9130, 10330,
        11530]])

In [45]:
a=np.array([[1,2],[3,4]])
b=np.array([[3,4],[5,6]])
np.dot(a,b)

array([[13, 16],
       [29, 36]])

In [46]:
a*b

array([[ 3,  8],
       [15, 24]])

In [47]:
b*a

array([[ 3,  8],
       [15, 24]])

In [56]:
np.swapaxes(a,0,1)

array([[1, 3],
       [2, 4]])

In [59]:
numbers=np.array([6,7,8,5,3,2,1])

In [64]:
np.sort(numbers)

array([1, 2, 3, 5, 6, 7, 8])

In [65]:
np.sqrt(numbers)

array([1.        , 1.41421356, 1.73205081, 2.23606798, 2.44948974,
       2.64575131, 2.82842712])

In [66]:
letters=np.array(['a','c','b','e','d'])

In [67]:
np.sort(letters)

array(['a', 'b', 'c', 'd', 'e'], dtype='|S1')

In [68]:
strings=np.array(['abc','aab','abb'])
np.sort(strings)

array(['aab', 'abb', 'abc'], dtype='|S3')

In [70]:
a=np.array(['a','b','c'])
b=np.array(['a','b','c'])

In [73]:
a,b

(array(['a', 'b', 'c'], dtype='|S1'), array(['a', 'b', 'c'], dtype='|S1'))

In [79]:
np.random.randn(4)

array([-0.01250279,  0.48985835, -0.26842056, -1.69861665])

In [80]:
np.random.randn(4)

array([-0.77435953, -0.4286476 , -1.43770088,  0.42419909])

In [83]:
values=np.random.rand(5)%10+2

In [84]:
values

array([2.78980524, 2.61252654, 2.3805993 , 2.14655576, 2.21658662])

In [86]:
values.max()

2.7898052355434952

In [87]:
first=np.array([5,1,2,7])
second=np.array([1,4,4,2])
np.maximum(first,second)

array([5, 4, 4, 7])

In [88]:
import webbrowser

In [89]:
webbrowser.open('https://www.youtube.com/')

True