In [4]:
import numpy as np
from numpy.random import randn 

In [5]:
arr=np.array([1,2,3,4,5])
np.save('myarray',arr)

In [6]:
np.load('myarray.npy')

array([1, 2, 3, 4, 5])

In [7]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])

In [14]:
np.savez('zip_array',x=a1,y=a2)

In [15]:
res=np.load('zip_array.npz')

In [16]:
res['x']

array([1, 2, 3, 4])

In [17]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [18]:
np.savez('zip_array2',a,b)

In [19]:
res=np.load('zip_array2.npz')

In [25]:
#removing

In [28]:
rm zip_array2.npz

SyntaxError: invalid syntax (<ipython-input-28-936a33a0de33>, line 1)

In [34]:
a=np.array([1,2,3,4,5,6,7])


In [38]:
np.delete(a,[1,2,6])

array([1, 4, 5, 6])

In [36]:
b=np.array([1,1,2,2,2,3,4,3,5,6,7])

In [39]:
#(array,indexes)
np.delete(b,[1,2,3])

array([1, 2, 3, 4, 3, 5, 6, 7])

In [54]:
a=np.array([1,2,3])

In [55]:
np.savetxt('names.txt',a,delimiter=',')

In [56]:
np.loadtxt('names.txt')

array([1., 2., 3.])

In [62]:
#string nile kaj korena
name=np.array([['sondip'],['susmoy']])

In [65]:
np.savetxt('names.txt',name,delimiter=',')

TypeError: Mismatch between array dtype ('|S6') and format specifier ('%.18e')